In [5]:
import numpy as np
import pandas as pd

#First using pandas we load the CSV file
df = pd.read_csv('supermarket_sales.csv')

#Using pandas we validate the top 5 sales for each payment ordering by the quantity
top5Payment = df.sort_values(by=['Payment','Total'], ascending =[True, False]).groupby('Payment').head(5)

#Obtaning the payment and total for each one into Array from the pandas
data = df[['Payment', 'Total']].to_numpy()

#We checked the unique payments that are in the Array, selection the 0 position because payment is stored in that position
payments = np.unique(data[:, 0])

#Using a cicle for the number of payments
for paymet in payments:
    
    #Using a validation we checked the payment in the array, thos should be in the main array getting the data wich is in payment from all the Array
    position = data[:, 0] == paymet

    #using a mask we stract the data but related to the payment that is iterating the cicle
    subset = data[position]

    #In a new Array we storage all the data from the position 1 that is the total getting all the totals into a new Array
    quantities = subset[:, 1].astype(float)

    #We passed from the quantities in this case total sorting from Higher to Lower and just getting the firts 5 because are the top 5 in Total higher
    idTop = np.argsort(quantities)[::-1][:5] 

    #Just select the top 5 from the subset that just contains the payment we are iterating.
    topRows = subset[idTop]

    #Print on screen data related to the payment
    print(f"\nPayment Method: {paymet}")
    print(topRows)

Payment Method: Cash
[['Cash' 1003.59]
 ['Cash' 1002.12]
 ['Cash' 950.25]
 ['Cash' 943.299]
 ['Cash' 935.2665]]

Payment Method: Credit card
[['Credit card' 1042.65]
 ['Credit card' 1039.29]
 ['Credit card' 1022.385]
 ['Credit card' 1020.705]
 ['Credit card' 944.622]]

Payment Method: Ewallet
[['Ewallet' 1034.46]
 ['Ewallet' 1023.75]
 ['Ewallet' 1022.49]
 ['Ewallet' 951.825]
 ['Ewallet' 937.818]]

In [4]:
top5Payment

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
166,234-65-2137,C,Naypyitaw,Normal,Male,Home and lifestyle,95.58,10,47.7900,1003.5900,1/16/2019,13:32,Cash,955.80,4.761905,47.7900,4.8
357,554-42-2417,C,Naypyitaw,Normal,Female,Sports and travel,95.44,10,47.7200,1002.1200,1/9/2019,13:45,Cash,954.40,4.761905,47.7200,5.2
141,280-17-4359,C,Naypyitaw,Member,Male,Health and beauty,90.50,10,45.2500,950.2500,1/25/2019,13:48,Cash,905.00,4.761905,45.2500,8.1
941,702-83-5291,C,Naypyitaw,Member,Male,Fashion accessories,99.82,9,44.9190,943.2990,3/27/2019,10:43,Cash,898.38,4.761905,44.9190,6.6
611,277-35-5865,C,Naypyitaw,Member,Female,Food and beverages,98.97,9,44.5365,935.2665,3/9/2019,11:23,Cash,890.73,4.761905,44.5365,6.7
350,860-79-0874,C,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,14:53,Credit card,993.00,4.761905,49.6500,6.6
167,687-47-8271,A,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,16:20,Credit card,989.80,4.761905,49.4900,8.7
792,744-16-7898,B,Mandalay,Normal,Female,Home and lifestyle,97.37,10,48.6850,1022.3850,1/15/2019,13:48,Credit card,973.70,4.761905,48.6850,4.9
422,271-88-8734,C,Naypyitaw,Member,Female,Fashion accessories,97.21,10,48.6050,1020.7050,2/8/2019,13:00,Credit card,972.10,4.761905,48.6050,8.7
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.9820,944.6220,3/9/2019,17:26,Credit card,899.64,4.761905,44.9820,4.2
557,283-26-5248,C,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,20:23,Ewallet,985.20,4.761905,49.2600,4.5
699,751-41-9720,C,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,16:18,Ewallet,975.00,4.761905,48.7500,8.0
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
429,325-77-6186,A,Yangon,Member,Female,Home and lifestyle,90.65,10,45.3250,951.8250,3/8/2019,10:53,Ewallet,906.50,4.761905,45.3250,7.3
435,751-69-0068,C,Naypyitaw,Normal,Male,Sports and travel,99.24,9,44.6580,937.8180,3/19/2019,19:09,Ewallet,893.16,4.761905,44.6580,9.0